databases:
  - name: postgres
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: Joker
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: bash start
    region: frankfurt
    repo: https://github.com/LLLP7/ahmed      
    branch: master
    envVars:
      - key: MUSIC_BOT_NAME
        value: Linda music
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_DB_URI
        value: mongodb+srv://YaFa:alhajji999@yafa.ckoem7a.mongodb.net/mohmed20034?retryWrites=true&w=majority
      - key: LOG_GROUP_ID
        sync: false
      - key: OWNER_ID
        sync: false
        fromDatabase:
          name: postgres
          property: connectionString   
    autoDeploy: false
